import type { OccasionType, LocationType, TimeType, SettingType, BudgetType } from '@/types/praxis';

// ============= OUTFIT MATRIX =============
// Internal-only expanded library with clustering for intelligent selection
// Each outfit is tagged with multiple attributes for precise matching

// ============= CLUSTER TYPES =============
export type SkinToneFit = 'cool' | 'warm' | 'neutral';
export type ContrastFit = 'low' | 'medium' | 'high';
export type BodyTypeFit = 'slim' | 'athletic' | 'broader';
export type TasteFit = 'minimalist' | 'classic' | 'elevated';
export type VibeFit = 'safe' | 'sharp' | 'relaxed';

export type TierType = 'SAFEST' | 'SHARPER' | 'RELAXED';

// ============= ENHANCED OUTFIT ENTRY =============
export interface MatrixOutfitEntry {
  id: string;
  occasion: OccasionType;
  tier: TierType;
  
  // Context filters
  location: LocationType[];
  time: TimeType[];
  setting: SettingType[];
  budget: BudgetType[];
  
  // Cluster attributes (internal selection)
  skin_tone_fit: SkinToneFit[];
  contrast_fit: ContrastFit[];
  body_type_fit: BodyTypeFit[];
  taste_fit: TasteFit[];
  vibe: VibeFit;
  
  // Formality and confidence
  formality_level: 1 | 2 | 3 | 4 | 5; // 1=casual, 5=formal
  confidence_score: number; // 1-10, higher = more universally flattering
  
  // Visual details
  palette: string[]; // Colors used (for visual consistency check)
  image_url: string;
  
  // Content
  title: string;
  items: {
    top: string;
    bottom: string;
    shoes: string;
    extras?: string;
  };
  reason: string;
}

// ============= OUTFIT MATRIX DATA =============
// Each occasion has 15-24 outfits organized by cluster
// Selection logic picks best 3 based on user profile

export const OUTFIT_MATRIX: MatrixOutfitEntry[] = [
  // =============================================
  // DATE - 18 outfits (6 per tier)
  // =============================================
  
  // DATE - SAFEST (6 variants)
  {
    id: "date_safest_cool_01",
    occasion: "DATE",
    tier: "SAFEST",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["navy", "white", "charcoal"],
    image_url: "/images/date_safest_01.jpg",
    title: "Cool Classic",
    items: {
      top: "Navy overshirt with a white t-shirt",
      bottom: "Charcoal straight jeans",
      shoes: "Clean white sneakers",
    },
    reason: "A refined look with cool tones that enhances natural coloring.",
  },
  {
    id: "date_safest_warm_01",
    occasion: "DATE",
    tier: "SAFEST",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["olive", "cream", "tan"],
    image_url: "/images/date_safest_01.jpg",
    title: "Warm Casual",
    items: {
      top: "Olive overshirt with a cream t-shirt",
      bottom: "Dark tan straight jeans",
      shoes: "Clean white sneakers",
    },
    reason: "Warm, grounded tones that complement your complexion naturally.",
  },
  {
    id: "date_safest_neutral_01",
    occasion: "DATE",
    tier: "SAFEST",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 9,
    palette: ["slate", "off-white", "dark grey"],
    image_url: "/images/date_safest_01.jpg",
    title: "Clean and Relaxed",
    items: {
      top: "Neutral overshirt with a plain t-shirt",
      bottom: "Dark straight jeans",
      shoes: "Clean white sneakers",
    },
    reason: "A safe, confident look that feels natural for a date night.",
  },
  {
    id: "date_safest_broader_01",
    occasion: "DATE",
    tier: "SAFEST",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["charcoal", "slate", "dark navy"],
    image_url: "/images/date_safest_01.jpg",
    title: "Structured Casual",
    items: {
      top: "Structured overshirt in charcoal with a slate tee",
      bottom: "Dark straight-leg jeans",
      shoes: "Clean leather sneakers",
    },
    reason: "Clean vertical lines that create a balanced, grounded silhouette.",
  },
  {
    id: "date_safest_slim_01",
    occasion: "DATE",
    tier: "SAFEST",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["charcoal", "light grey", "white"],
    image_url: "/images/date_safest_01.jpg",
    title: "Layered Minimal",
    items: {
      top: "Light textured knit layered under a charcoal overshirt",
      bottom: "Dark slim jeans",
      shoes: "Clean white sneakers",
    },
    reason: "Layering adds dimension while keeping the look effortlessly clean.",
  },
  {
    id: "date_safest_highcontrast_01",
    occasion: "DATE",
    tier: "SAFEST",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["black", "white", "charcoal"],
    image_url: "/images/date_safest_01.jpg",
    title: "Crisp Contrast",
    items: {
      top: "Black overshirt with a crisp white t-shirt",
      bottom: "Dark charcoal jeans",
      shoes: "Clean white sneakers",
    },
    reason: "Bold contrast that matches your natural coloring for maximum impact.",
  },
  
  // DATE - SHARPER (6 variants)
  {
    id: "date_sharper_cool_01",
    occasion: "DATE",
    tier: "SHARPER",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["navy", "charcoal", "white"],
    image_url: "/images/date_sharper_01.jpg",
    title: "Cool Refined",
    items: {
      top: "Navy blazer over a fine charcoal knit",
      bottom: "Tailored charcoal trousers",
      shoes: "Leather loafers",
    },
    reason: "Sharp cool tones that elevate without overdoing it.",
  },
  {
    id: "date_sharper_warm_01",
    occasion: "DATE",
    tier: "SHARPER",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["camel", "navy", "cream"],
    image_url: "/images/date_sharper_01.jpg",
    title: "Warm Polish",
    items: {
      top: "Camel blazer over a cream fine knit",
      bottom: "Navy tailored chinos",
      shoes: "Brown leather loafers",
    },
    reason: "Warm, sophisticated tones that feel polished and intentional.",
  },
  {
    id: "date_sharper_neutral_01",
    occasion: "DATE",
    tier: "SHARPER",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["navy", "grey", "white"],
    image_url: "/images/date_sharper_01.jpg",
    title: "Smart Casual",
    items: {
      top: "Navy blazer over a fine knit top",
      bottom: "Tailored chinos",
      shoes: "Loafers",
    },
    reason: "More polished without looking like you tried too hard.",
  },
  {
    id: "date_sharper_broader_01",
    occasion: "DATE",
    tier: "SHARPER",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["charcoal", "slate", "navy"],
    image_url: "/images/date_sharper_01.jpg",
    title: "Structured Sharp",
    items: {
      top: "Unstructured charcoal blazer over a slate knit",
      bottom: "Navy tailored trousers with straight leg",
      shoes: "Leather loafers",
    },
    reason: "Soft structure creates polish without adding unnecessary bulk.",
  },
  {
    id: "date_sharper_slim_01",
    occasion: "DATE",
    tier: "SHARPER",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["black", "charcoal", "grey"],
    image_url: "/images/date_sharper_01.jpg",
    title: "Sleek Sharp",
    items: {
      top: "Slim-cut black blazer over a charcoal knit",
      bottom: "Slim tailored grey trousers",
      shoes: "Black leather loafers",
    },
    reason: "Clean lines and dimension that work with a lean frame.",
  },
  {
    id: "date_sharper_elevated_01",
    occasion: "DATE",
    tier: "SHARPER",
    location: ["RESTAURANT", "BAR"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["midnight navy", "white", "black"],
    image_url: "/images/date_sharper_01.jpg",
    title: "Elevated Evening",
    items: {
      top: "Midnight navy blazer over a crisp white shirt",
      bottom: "Black tailored trousers",
      shoes: "Black leather loafers",
    },
    reason: "High contrast that commands attention with refined elegance.",
  },
  
  // DATE - RELAXED (6 variants)
  {
    id: "date_relaxed_cool_01",
    occasion: "DATE",
    tier: "RELAXED",
    location: ["RESTAURANT", "BAR", "HOME"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["grey", "navy", "white"],
    image_url: "/images/date_relaxed_01.jpg",
    title: "Cool Easy",
    items: {
      top: "Grey t-shirt with a light navy jacket",
      bottom: "Dark slim jeans",
      shoes: "Clean casual sneakers",
    },
    reason: "Cool, relaxed tones for an effortless date look.",
  },
  {
    id: "date_relaxed_warm_01",
    occasion: "DATE",
    tier: "RELAXED",
    location: ["RESTAURANT", "BAR", "HOME"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["off-white", "olive", "brown"],
    image_url: "/images/date_relaxed_01.jpg",
    title: "Warm Weekend",
    items: {
      top: "Off-white t-shirt with a light olive jacket",
      bottom: "Dark brown slim jeans",
      shoes: "Tan casual sneakers",
    },
    reason: "Warm, grounded tones for a relaxed, approachable look.",
  },
  {
    id: "date_relaxed_neutral_01",
    occasion: "DATE",
    tier: "RELAXED",
    location: ["RESTAURANT", "BAR", "HOME"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 9,
    palette: ["grey", "navy", "white"],
    image_url: "/images/date_relaxed_01.jpg",
    title: "Easy Weekend",
    items: {
      top: "Plain t-shirt with a light jacket",
      bottom: "Slim dark jeans",
      shoes: "Casual sneakers",
    },
    reason: "Comfort-first while still looking put together.",
  },
  {
    id: "date_relaxed_broader_01",
    occasion: "DATE",
    tier: "RELAXED",
    location: ["RESTAURANT", "BAR", "HOME"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["charcoal", "slate", "dark blue"],
    image_url: "/images/date_relaxed_01.jpg",
    title: "Easy Structure",
    items: {
      top: "Slate t-shirt with a structured charcoal jacket",
      bottom: "Dark straight-leg jeans",
      shoes: "Clean leather sneakers",
    },
    reason: "Relaxed with enough structure to create a balanced silhouette.",
  },
  {
    id: "date_relaxed_slim_01",
    occasion: "DATE",
    tier: "RELAXED",
    location: ["RESTAURANT", "BAR", "HOME"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["light grey", "charcoal", "white"],
    image_url: "/images/date_relaxed_01.jpg",
    title: "Layered Casual",
    items: {
      top: "Light grey t-shirt with a charcoal cardigan",
      bottom: "Dark slim jeans",
      shoes: "White casual sneakers",
    },
    reason: "Layering adds visual interest while keeping things relaxed.",
  },
  {
    id: "date_relaxed_lowcontrast_01",
    occasion: "DATE",
    tier: "RELAXED",
    location: ["RESTAURANT", "BAR", "HOME"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["low"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["soft grey", "taupe", "cream"],
    image_url: "/images/date_relaxed_01.jpg",
    title: "Soft Tonal",
    items: {
      top: "Soft grey t-shirt with a taupe jacket",
      bottom: "Dark cream chinos",
      shoes: "Off-white sneakers",
    },
    reason: "Soft, tonal palette that flows naturally with low-contrast features.",
  },
  
  // =============================================
  // WORK - 18 outfits (6 per tier)
  // =============================================
  
  // WORK - SAFEST (6 variants)
  {
    id: "work_safest_cool_01",
    occasion: "WORK",
    tier: "SAFEST",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 4,
    confidence_score: 9,
    palette: ["white", "charcoal", "black"],
    image_url: "/images/work_safest_01.jpg",
    title: "Cool Professional",
    items: {
      top: "Crisp white button-down shirt",
      bottom: "Charcoal tailored trousers",
      shoes: "Black leather lace-up shoes",
    },
    reason: "Clean, cool tones that project competence and clarity.",
  },
  {
    id: "work_safest_warm_01",
    occasion: "WORK",
    tier: "SAFEST",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 4,
    confidence_score: 8,
    palette: ["cream", "navy", "brown"],
    image_url: "/images/work_safest_01.jpg",
    title: "Warm Professional",
    items: {
      top: "Cream button-down shirt",
      bottom: "Navy tailored trousers",
      shoes: "Brown leather lace-up shoes",
    },
    reason: "Warm, approachable tones that feel professional and grounded.",
  },
  {
    id: "work_safest_neutral_01",
    occasion: "WORK",
    tier: "SAFEST",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 4,
    confidence_score: 9,
    palette: ["white", "grey", "black"],
    image_url: "/images/work_safest_01.jpg",
    title: "Professional Standard",
    items: {
      top: "Button-down shirt",
      bottom: "Tailored trousers",
      shoes: "Leather lace-up shoes",
    },
    reason: "A safe professional look that works in any office.",
  },
  {
    id: "work_safest_broader_01",
    occasion: "WORK",
    tier: "SAFEST",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 4,
    confidence_score: 8,
    palette: ["navy", "white", "charcoal"],
    image_url: "/images/work_safest_01.jpg",
    title: "Streamlined Professional",
    items: {
      top: "Navy button-down shirt",
      bottom: "Charcoal tailored trousers with straight leg",
      shoes: "Black leather shoes",
    },
    reason: "Vertical lines and dark tones create a streamlined, commanding presence.",
  },
  {
    id: "work_safest_slim_01",
    occasion: "WORK",
    tier: "SAFEST",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 4,
    confidence_score: 8,
    palette: ["light blue", "charcoal", "black"],
    image_url: "/images/work_safest_01.jpg",
    title: "Sharp Minimal",
    items: {
      top: "Fitted light blue button-down",
      bottom: "Slim charcoal tailored trousers",
      shoes: "Black leather shoes",
    },
    reason: "Clean, fitted lines for a sharp, professional impression.",
  },
  {
    id: "work_safest_highcontrast_01",
    occasion: "WORK",
    tier: "SAFEST",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 4,
    confidence_score: 9,
    palette: ["crisp white", "black", "charcoal"],
    image_url: "/images/work_safest_01.jpg",
    title: "High Contrast Pro",
    items: {
      top: "Crisp white button-down shirt",
      bottom: "Black tailored trousers",
      shoes: "Black leather shoes",
    },
    reason: "Sharp contrast that matches high-contrast features for maximum presence.",
  },
  
  // WORK - SHARPER (6 variants)
  {
    id: "work_sharper_cool_01",
    occasion: "WORK",
    tier: "SHARPER",
    location: ["OFFICE", "MEETING", "CONFERENCE"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 9,
    palette: ["charcoal", "white", "black"],
    image_url: "/images/work_sharper_01.jpg",
    title: "Cool Authority",
    items: {
      top: "Charcoal blazer over a crisp white shirt",
      bottom: "Charcoal tailored trousers",
      shoes: "Black oxfords",
    },
    reason: "Cool, authoritative tones for commanding presence.",
  },
  {
    id: "work_sharper_warm_01",
    occasion: "WORK",
    tier: "SHARPER",
    location: ["OFFICE", "MEETING", "CONFERENCE"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 8,
    palette: ["navy", "cream", "brown"],
    image_url: "/images/work_sharper_01.jpg",
    title: "Warm Authority",
    items: {
      top: "Navy blazer over a cream shirt",
      bottom: "Navy tailored trousers",
      shoes: "Brown oxfords",
    },
    reason: "Warm sophistication that commands respect without coldness.",
  },
  {
    id: "work_sharper_neutral_01",
    occasion: "WORK",
    tier: "SHARPER",
    location: ["OFFICE", "MEETING", "CONFERENCE"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 9,
    palette: ["navy", "white", "charcoal"],
    image_url: "/images/work_sharper_01.jpg",
    title: "Sharp Professional",
    items: {
      top: "Blazer over a crisp shirt",
      bottom: "Tailored trousers",
      shoes: "Oxfords",
    },
    reason: "Sharper choice when you want to look in control.",
  },
  {
    id: "work_sharper_broader_01",
    occasion: "WORK",
    tier: "SHARPER",
    location: ["OFFICE", "MEETING", "CONFERENCE"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 8,
    palette: ["charcoal", "navy", "black"],
    image_url: "/images/work_sharper_01.jpg",
    title: "Powerful Structure",
    items: {
      top: "Unstructured charcoal blazer over a navy shirt",
      bottom: "Charcoal tailored trousers with straight leg",
      shoes: "Black oxfords",
    },
    reason: "Soft structure and dark tones for commanding presence without bulk.",
  },
  {
    id: "work_sharper_slim_01",
    occasion: "WORK",
    tier: "SHARPER",
    location: ["OFFICE", "MEETING", "CONFERENCE"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 8,
    palette: ["black", "white", "charcoal"],
    image_url: "/images/work_sharper_01.jpg",
    title: "Modern Sharp",
    items: {
      top: "Slim black blazer over a crisp white shirt",
      bottom: "Slim charcoal tailored trousers",
      shoes: "Black leather oxfords",
    },
    reason: "Clean modern lines for sharp, contemporary authority.",
  },
  {
    id: "work_sharper_elevated_01",
    occasion: "WORK",
    tier: "SHARPER",
    location: ["OFFICE", "MEETING", "CONFERENCE"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 9,
    palette: ["midnight navy", "crisp white", "black"],
    image_url: "/images/work_sharper_01.jpg",
    title: "Executive Sharp",
    items: {
      top: "Midnight navy blazer over a crisp white shirt",
      bottom: "Black tailored trousers",
      shoes: "Black leather oxfords",
      extras: "Silver cufflinks",
    },
    reason: "High-contrast executive presence for important moments.",
  },
  
  // WORK - RELAXED (6 variants)
  {
    id: "work_relaxed_cool_01",
    occasion: "WORK",
    tier: "RELAXED",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 3,
    confidence_score: 8,
    palette: ["navy", "grey", "charcoal"],
    image_url: "/images/work_relaxed_01.jpg",
    title: "Cool Comfortable",
    items: {
      top: "Navy fine knit polo",
      bottom: "Grey chinos",
      shoes: "Dark leather loafers",
    },
    reason: "Cool, comfortable tones for a relaxed but polished workday.",
  },
  {
    id: "work_relaxed_warm_01",
    occasion: "WORK",
    tier: "RELAXED",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 3,
    confidence_score: 8,
    palette: ["camel", "cream", "tan"],
    image_url: "/images/work_relaxed_01.jpg",
    title: "Warm Comfortable",
    items: {
      top: "Camel fine knit sweater",
      bottom: "Tan chinos",
      shoes: "Brown leather loafers",
    },
    reason: "Warm, inviting tones for an approachable workday look.",
  },
  {
    id: "work_relaxed_neutral_01",
    occasion: "WORK",
    tier: "RELAXED",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 3,
    confidence_score: 9,
    palette: ["grey", "navy", "tan"],
    image_url: "/images/work_relaxed_01.jpg",
    title: "Modern Workwear",
    items: {
      top: "Knit polo or fine sweater",
      bottom: "Chinos",
      shoes: "Loafers",
    },
    reason: "Comfortable while still looking professional.",
  },
  {
    id: "work_relaxed_broader_01",
    occasion: "WORK",
    tier: "RELAXED",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 3,
    confidence_score: 8,
    palette: ["charcoal", "navy", "slate"],
    image_url: "/images/work_relaxed_01.jpg",
    title: "Relaxed Structure",
    items: {
      top: "Structured navy polo",
      bottom: "Charcoal chinos with straight leg",
      shoes: "Dark leather loafers",
    },
    reason: "Relaxed formality with clean lines for a balanced look.",
  },
  {
    id: "work_relaxed_slim_01",
    occasion: "WORK",
    tier: "RELAXED",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 3,
    confidence_score: 8,
    palette: ["light grey", "navy", "white"],
    image_url: "/images/work_relaxed_01.jpg",
    title: "Light Minimal",
    items: {
      top: "Light grey fine knit sweater",
      bottom: "Navy slim chinos",
      shoes: "White leather loafers",
    },
    reason: "Light, clean layers for a fresh, relaxed workday.",
  },
  {
    id: "work_relaxed_lowcontrast_01",
    occasion: "WORK",
    tier: "RELAXED",
    location: ["OFFICE", "MEETING"],
    time: ["DAY"],
    setting: ["INDOOR"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["low"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 3,
    confidence_score: 8,
    palette: ["taupe", "cream", "soft grey"],
    image_url: "/images/work_relaxed_01.jpg",
    title: "Soft Professional",
    items: {
      top: "Soft taupe fine knit",
      bottom: "Cream chinos",
      shoes: "Taupe leather loafers",
    },
    reason: "Soft, tonal palette for a refined, understated presence.",
  },
  
  // =============================================
  // DINNER - 18 outfits (6 per tier)
  // =============================================
  
  // DINNER - SAFEST (6 variants)
  {
    id: "dinner_safest_cool_01",
    occasion: "DINNER",
    tier: "SAFEST",
    location: ["RESTAURANT", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["navy", "charcoal", "grey"],
    image_url: "/images/dinner_safest_01.jpg",
    title: "Cool Polished",
    items: {
      top: "Navy knit top",
      bottom: "Charcoal clean chinos",
      shoes: "Grey leather sneakers",
    },
    reason: "Cool, refined tones for an understated dinner look.",
  },
  {
    id: "dinner_safest_warm_01",
    occasion: "DINNER",
    tier: "SAFEST",
    location: ["RESTAURANT", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["olive", "cream", "tan"],
    image_url: "/images/dinner_safest_01.jpg",
    title: "Warm Polished",
    items: {
      top: "Olive knit top",
      bottom: "Tan clean chinos",
      shoes: "Cream leather sneakers",
    },
    reason: "Warm, earthy tones for a grounded, inviting dinner look.",
  },
  {
    id: "dinner_safest_neutral_01",
    occasion: "DINNER",
    tier: "SAFEST",
    location: ["RESTAURANT", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 9,
    palette: ["charcoal", "grey", "white"],
    image_url: "/images/dinner_safest_01.jpg",
    title: "Polished Casual",
    items: {
      top: "Dark knit top",
      bottom: "Clean chinos",
      shoes: "Leather sneakers",
    },
    reason: "Simple and polished for a dinner without overdoing it.",
  },
  {
    id: "dinner_safest_broader_01",
    occasion: "DINNER",
    tier: "SAFEST",
    location: ["RESTAURANT", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["navy", "charcoal", "slate"],
    image_url: "/images/dinner_safest_01.jpg",
    title: "Balanced Polish",
    items: {
      top: "Navy structured knit",
      bottom: "Charcoal straight-leg chinos",
      shoes: "Dark leather sneakers",
    },
    reason: "Dark vertical lines create a balanced, refined dinner look.",
  },
  {
    id: "dinner_safest_slim_01",
    occasion: "DINNER",
    tier: "SAFEST",
    location: ["RESTAURANT", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["grey", "charcoal", "white"],
    image_url: "/images/dinner_safest_01.jpg",
    title: "Minimal Evening",
    items: {
      top: "Light grey textured knit",
      bottom: "Charcoal slim chinos",
      shoes: "White leather sneakers",
    },
    reason: "Subtle texture adds dimension without complexity.",
  },
  {
    id: "dinner_safest_highcontrast_01",
    occasion: "DINNER",
    tier: "SAFEST",
    location: ["RESTAURANT", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["black", "white", "charcoal"],
    image_url: "/images/dinner_safest_01.jpg",
    title: "Sharp Casual",
    items: {
      top: "Black knit top",
      bottom: "Charcoal clean chinos",
      shoes: "White leather sneakers",
    },
    reason: "Bold contrast for a clean, impactful dinner look.",
  },
  
  // DINNER - SHARPER (6 variants)
  {
    id: "dinner_sharper_cool_01",
    occasion: "DINNER",
    tier: "SHARPER",
    location: ["RESTAURANT", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["charcoal", "navy", "black"],
    image_url: "/images/dinner_sharper_01.jpg",
    title: "Cool Elevated",
    items: {
      top: "Charcoal blazer over a navy fitted knit",
      bottom: "Black tailored trousers",
      shoes: "Black Chelsea boots",
    },
    reason: "Cool sophistication for a memorable dinner.",
  },
  {
    id: "dinner_sharper_warm_01",
    occasion: "DINNER",
    tier: "SHARPER",
    location: ["RESTAURANT", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["camel", "burgundy", "navy"],
    image_url: "/images/dinner_sharper_01.jpg",
    title: "Warm Elevated",
    items: {
      top: "Camel blazer over a burgundy knit",
      bottom: "Navy tailored trousers",
      shoes: "Brown Chelsea boots",
    },
    reason: "Rich, warm tones for an elevated dinner presence.",
  },
  {
    id: "dinner_sharper_neutral_01",
    occasion: "DINNER",
    tier: "SHARPER",
    location: ["RESTAURANT", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["navy", "grey", "black"],
    image_url: "/images/dinner_sharper_01.jpg",
    title: "Elevated Dinner",
    items: {
      top: "Blazer over a fitted knit",
      bottom: "Tailored trousers",
      shoes: "Chelsea boots",
    },
    reason: "A sharper option that looks intentional and clean.",
  },
  {
    id: "dinner_sharper_broader_01",
    occasion: "DINNER",
    tier: "SHARPER",
    location: ["RESTAURANT", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["charcoal", "slate", "navy"],
    image_url: "/images/dinner_sharper_01.jpg",
    title: "Structured Elegance",
    items: {
      top: "Unstructured charcoal blazer over a slate knit",
      bottom: "Navy tailored trousers with straight leg",
      shoes: "Black Chelsea boots",
    },
    reason: "Soft structure for elevated presence without bulk.",
  },
  {
    id: "dinner_sharper_slim_01",
    occasion: "DINNER",
    tier: "SHARPER",
    location: ["RESTAURANT", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["black", "charcoal", "grey"],
    image_url: "/images/dinner_sharper_01.jpg",
    title: "Modern Evening",
    items: {
      top: "Slim black blazer over a charcoal knit",
      bottom: "Slim grey tailored trousers",
      shoes: "Black Chelsea boots",
    },
    reason: "Modern minimalism for a sharp dinner look.",
  },
  {
    id: "dinner_sharper_elevated_01",
    occasion: "DINNER",
    tier: "SHARPER",
    location: ["RESTAURANT", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["midnight navy", "black", "white"],
    image_url: "/images/dinner_sharper_01.jpg",
    title: "Statement Evening",
    items: {
      top: "Midnight navy blazer over a black knit",
      bottom: "Black tailored trousers",
      shoes: "Black leather Chelsea boots",
      extras: "Silver watch",
    },
    reason: "High-impact elegance for special dinner occasions.",
  },
  
  // DINNER - RELAXED (6 variants)
  {
    id: "dinner_relaxed_cool_01",
    occasion: "DINNER",
    tier: "RELAXED",
    location: ["RESTAURANT", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["grey", "navy", "white"],
    image_url: "/images/dinner_relaxed_01.jpg",
    title: "Cool Casual",
    items: {
      top: "Grey t-shirt with a light navy overshirt",
      bottom: "Dark jeans",
      shoes: "Clean white sneakers",
    },
    reason: "Cool, relaxed tones for an easy dinner look.",
  },
  {
    id: "dinner_relaxed_warm_01",
    occasion: "DINNER",
    tier: "RELAXED",
    location: ["RESTAURANT", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["cream", "olive", "brown"],
    image_url: "/images/dinner_relaxed_01.jpg",
    title: "Warm Casual",
    items: {
      top: "Cream t-shirt with an olive overshirt",
      bottom: "Dark brown jeans",
      shoes: "Tan clean sneakers",
    },
    reason: "Warm, earthy tones for a relaxed, inviting dinner.",
  },
  {
    id: "dinner_relaxed_neutral_01",
    occasion: "DINNER",
    tier: "RELAXED",
    location: ["RESTAURANT", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 9,
    palette: ["grey", "navy", "charcoal"],
    image_url: "/images/dinner_relaxed_01.jpg",
    title: "Relaxed Clean",
    items: {
      top: "Plain t-shirt with a light overshirt",
      bottom: "Dark jeans",
      shoes: "Clean sneakers",
    },
    reason: "Relaxed choice that still looks neat for dinner.",
  },
  {
    id: "dinner_relaxed_broader_01",
    occasion: "DINNER",
    tier: "RELAXED",
    location: ["RESTAURANT", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["charcoal", "slate", "dark navy"],
    image_url: "/images/dinner_relaxed_01.jpg",
    title: "Relaxed Balance",
    items: {
      top: "Slate t-shirt with a charcoal overshirt",
      bottom: "Dark straight-leg jeans",
      shoes: "Dark leather sneakers",
    },
    reason: "Relaxed with clean lines for a balanced casual look.",
  },
  {
    id: "dinner_relaxed_slim_01",
    occasion: "DINNER",
    tier: "RELAXED",
    location: ["RESTAURANT", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["light grey", "charcoal", "white"],
    image_url: "/images/dinner_relaxed_01.jpg",
    title: "Light Layers",
    items: {
      top: "Light grey t-shirt with a charcoal cardigan",
      bottom: "Dark slim jeans",
      shoes: "White clean sneakers",
    },
    reason: "Light layering for an easy, put-together dinner look.",
  },
  {
    id: "dinner_relaxed_lowcontrast_01",
    occasion: "DINNER",
    tier: "RELAXED",
    location: ["RESTAURANT", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["low"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["soft grey", "taupe", "cream"],
    image_url: "/images/dinner_relaxed_01.jpg",
    title: "Soft Evening",
    items: {
      top: "Soft grey t-shirt with a taupe overshirt",
      bottom: "Dark cream jeans",
      shoes: "Off-white sneakers",
    },
    reason: "Soft, tonal palette for an understated dinner look.",
  },
  
  // =============================================
  // PARTY - 18 outfits (6 per tier)
  // =============================================
  
  // PARTY - SAFEST (6 variants)
  {
    id: "party_safest_cool_01",
    occasion: "PARTY",
    tier: "SAFEST",
    location: ["BAR", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["black", "charcoal", "grey"],
    image_url: "/images/party_safest_01.jpg",
    title: "Cool Night",
    items: {
      top: "Charcoal t-shirt with a black clean jacket",
      bottom: "Dark charcoal jeans",
      shoes: "Grey leather sneakers",
    },
    reason: "Cool, understated tones for a confident party presence.",
  },
  {
    id: "party_safest_warm_01",
    occasion: "PARTY",
    tier: "SAFEST",
    location: ["BAR", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["olive", "cream", "dark brown"],
    image_url: "/images/party_safest_01.jpg",
    title: "Warm Night",
    items: {
      top: "Cream t-shirt with an olive jacket",
      bottom: "Dark brown jeans",
      shoes: "Tan leather sneakers",
    },
    reason: "Warm, grounded tones for an approachable party look.",
  },
  {
    id: "party_safest_neutral_01",
    occasion: "PARTY",
    tier: "SAFEST",
    location: ["BAR", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 9,
    palette: ["black", "grey", "charcoal"],
    image_url: "/images/party_safest_01.jpg",
    title: "Night Out Basic",
    items: {
      top: "Black t-shirt with a clean jacket",
      bottom: "Dark jeans",
      shoes: "Leather sneakers",
    },
    reason: "Safe night-out look that always works.",
  },
  {
    id: "party_safest_broader_01",
    occasion: "PARTY",
    tier: "SAFEST",
    location: ["BAR", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["charcoal", "slate", "black"],
    image_url: "/images/party_safest_01.jpg",
    title: "Structured Night",
    items: {
      top: "Slate t-shirt with a structured charcoal jacket",
      bottom: "Black straight-leg jeans",
      shoes: "Dark leather sneakers",
    },
    reason: "Structure and dark tones for a commanding party presence.",
  },
  {
    id: "party_safest_slim_01",
    occasion: "PARTY",
    tier: "SAFEST",
    location: ["BAR", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["grey", "charcoal", "black"],
    image_url: "/images/party_safest_01.jpg",
    title: "Layered Night",
    items: {
      top: "Grey t-shirt with a charcoal jacket",
      bottom: "Black slim jeans",
      shoes: "Black leather sneakers",
    },
    reason: "Layering adds presence while keeping the look clean.",
  },
  {
    id: "party_safest_highcontrast_01",
    occasion: "PARTY",
    tier: "SAFEST",
    location: ["BAR", "HOME", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY", "MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 3,
    confidence_score: 8,
    palette: ["black", "white", "charcoal"],
    image_url: "/images/party_safest_01.jpg",
    title: "Bold Night",
    items: {
      top: "White t-shirt with a black jacket",
      bottom: "Black jeans",
      shoes: "Black leather sneakers",
    },
    reason: "High contrast that matches your features for maximum impact.",
  },
  
  // PARTY - SHARPER (6 variants)
  {
    id: "party_sharper_cool_01",
    occasion: "PARTY",
    tier: "SHARPER",
    location: ["BAR", "CLUB", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["black", "charcoal", "silver"],
    image_url: "/images/party_sharper_01.jpg",
    title: "Cool Statement",
    items: {
      top: "Black fitted shirt with a charcoal blazer",
      bottom: "Slim black trousers",
      shoes: "Black Chelsea boots",
      extras: "Silver watch",
    },
    reason: "Cool sophistication for standing out with intention.",
  },
  {
    id: "party_sharper_warm_01",
    occasion: "PARTY",
    tier: "SHARPER",
    location: ["BAR", "CLUB", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["burgundy", "navy", "gold"],
    image_url: "/images/party_sharper_01.jpg",
    title: "Warm Statement",
    items: {
      top: "Burgundy fitted knit with a navy blazer",
      bottom: "Navy slim trousers",
      shoes: "Brown Chelsea boots",
      extras: "Gold watch",
    },
    reason: "Rich, warm tones for a memorable party presence.",
  },
  {
    id: "party_sharper_neutral_01",
    occasion: "PARTY",
    tier: "SHARPER",
    location: ["BAR", "CLUB", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["black", "charcoal", "grey"],
    image_url: "/images/party_sharper_01.jpg",
    title: "Sharp Statement",
    items: {
      top: "Black shirt or fitted knit with a blazer",
      bottom: "Slim dark trousers",
      shoes: "Chelsea boots",
    },
    reason: "Sharper choice if you want to stand out in a clean way.",
  },
  {
    id: "party_sharper_broader_01",
    occasion: "PARTY",
    tier: "SHARPER",
    location: ["BAR", "CLUB", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["charcoal", "navy", "black"],
    image_url: "/images/party_sharper_01.jpg",
    title: "Powerful Night",
    items: {
      top: "Navy fitted knit with an unstructured charcoal blazer",
      bottom: "Black straight-leg trousers",
      shoes: "Black Chelsea boots",
    },
    reason: "Soft structure and dark tones for commanding presence.",
  },
  {
    id: "party_sharper_slim_01",
    occasion: "PARTY",
    tier: "SHARPER",
    location: ["BAR", "CLUB", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 8,
    palette: ["all black", "charcoal"],
    image_url: "/images/party_sharper_01.jpg",
    title: "Sleek Statement",
    items: {
      top: "Black fitted shirt with a slim black blazer",
      bottom: "Black slim trousers",
      shoes: "Black leather Chelsea boots",
    },
    reason: "All-black sleekness for maximum statement.",
  },
  {
    id: "party_sharper_elevated_01",
    occasion: "PARTY",
    tier: "SHARPER",
    location: ["BAR", "CLUB", "HOTEL"],
    time: ["NIGHT"],
    setting: ["INDOOR"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["elevated"],
    vibe: "sharp",
    formality_level: 4,
    confidence_score: 9,
    palette: ["midnight", "black", "silver"],
    image_url: "/images/party_sharper_01.jpg",
    title: "Elite Night",
    items: {
      top: "Midnight shirt with a black tailored blazer",
      bottom: "Black tailored trousers",
      shoes: "Black leather Chelsea boots",
      extras: "Silver cufflinks",
    },
    reason: "Elevated elegance for unforgettable nights.",
  },
  
  // PARTY - RELAXED (6 variants)
  {
    id: "party_relaxed_cool_01",
    occasion: "PARTY",
    tier: "RELAXED",
    location: ["BAR", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["grey", "navy", "charcoal"],
    image_url: "/images/party_relaxed_01.jpg",
    title: "Cool Easy",
    items: {
      top: "Navy bomber jacket over a grey t-shirt",
      bottom: "Dark charcoal jeans",
      shoes: "Grey casual sneakers",
    },
    reason: "Cool, effortless tones for a laid-back party vibe.",
  },
  {
    id: "party_relaxed_warm_01",
    occasion: "PARTY",
    tier: "RELAXED",
    location: ["BAR", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["olive", "cream", "brown"],
    image_url: "/images/party_relaxed_01.jpg",
    title: "Warm Easy",
    items: {
      top: "Olive bomber jacket over a cream t-shirt",
      bottom: "Dark brown jeans",
      shoes: "Tan casual sneakers",
    },
    reason: "Warm, inviting tones for an approachable party look.",
  },
  {
    id: "party_relaxed_neutral_01",
    occasion: "PARTY",
    tier: "RELAXED",
    location: ["BAR", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 9,
    palette: ["black", "grey", "dark"],
    image_url: "/images/party_relaxed_01.jpg",
    title: "Relaxed Street",
    items: {
      top: "Bomber jacket over a plain t-shirt",
      bottom: "Dark jeans",
      shoes: "Casual sneakers",
    },
    reason: "Comfortable option that still fits a party vibe.",
  },
  {
    id: "party_relaxed_broader_01",
    occasion: "PARTY",
    tier: "RELAXED",
    location: ["BAR", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["charcoal", "slate", "black"],
    image_url: "/images/party_relaxed_01.jpg",
    title: "Relaxed Structure",
    items: {
      top: "Charcoal bomber jacket over a slate t-shirt",
      bottom: "Black straight-leg jeans",
      shoes: "Dark leather sneakers",
    },
    reason: "Relaxed with enough structure for a balanced look.",
  },
  {
    id: "party_relaxed_slim_01",
    occasion: "PARTY",
    tier: "RELAXED",
    location: ["BAR", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["grey", "black", "charcoal"],
    image_url: "/images/party_relaxed_01.jpg",
    title: "Street Layer",
    items: {
      top: "Black bomber jacket over a grey t-shirt",
      bottom: "Charcoal slim jeans",
      shoes: "Black casual sneakers",
    },
    reason: "Layered look that adds presence without overdoing it.",
  },
  {
    id: "party_relaxed_lowcontrast_01",
    occasion: "PARTY",
    tier: "RELAXED",
    location: ["BAR", "HOME"],
    time: ["NIGHT"],
    setting: ["INDOOR", "BOTH"],
    budget: ["EVERYDAY"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["low"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist"],
    vibe: "relaxed",
    formality_level: 2,
    confidence_score: 8,
    palette: ["soft grey", "taupe", "cream"],
    image_url: "/images/party_relaxed_01.jpg",
    title: "Soft Street",
    items: {
      top: "Taupe bomber jacket over a soft grey t-shirt",
      bottom: "Dark cream jeans",
      shoes: "Off-white sneakers",
    },
    reason: "Soft, tonal palette for an understated party presence.",
  },
  
  // =============================================
  // WEDDING - 18 outfits (6 per tier)
  // =============================================
  
  // WEDDING - SAFEST (6 variants)
  {
    id: "wedding_safest_cool_01",
    occasion: "WEDDING",
    tier: "SAFEST",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 5,
    confidence_score: 9,
    palette: ["charcoal", "white", "black"],
    image_url: "/images/wedding_safest_01.jpg",
    title: "Cool Classic",
    items: {
      top: "Charcoal suit with a crisp white shirt",
      bottom: "Matching suit trousers",
      shoes: "Black oxfords",
    },
    reason: "Cool, classic tones that are always wedding-appropriate.",
  },
  {
    id: "wedding_safest_warm_01",
    occasion: "WEDDING",
    tier: "SAFEST",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 5,
    confidence_score: 8,
    palette: ["navy", "cream", "brown"],
    image_url: "/images/wedding_safest_01.jpg",
    title: "Warm Classic",
    items: {
      top: "Navy suit with a cream shirt",
      bottom: "Matching suit trousers",
      shoes: "Brown oxfords",
    },
    reason: "Warm, sophisticated tones for a wedding look with personality.",
  },
  {
    id: "wedding_safest_neutral_01",
    occasion: "WEDDING",
    tier: "SAFEST",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 5,
    confidence_score: 9,
    palette: ["navy", "white", "black"],
    image_url: "/images/wedding_safest_01.jpg",
    title: "Classic Formal",
    items: {
      top: "Navy suit with a white shirt",
      bottom: "Matching suit trousers",
      shoes: "Black oxfords",
    },
    reason: "A classic wedding look that is always appropriate.",
  },
  {
    id: "wedding_safest_broader_01",
    occasion: "WEDDING",
    tier: "SAFEST",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 5,
    confidence_score: 8,
    palette: ["charcoal", "navy", "black"],
    image_url: "/images/wedding_safest_01.jpg",
    title: "Streamlined Formal",
    items: {
      top: "Charcoal suit with clean shoulders and a navy shirt",
      bottom: "Matching suit trousers with straight leg",
      shoes: "Black oxfords",
    },
    reason: "Dark, streamlined tailoring for a commanding formal presence.",
  },
  {
    id: "wedding_safest_slim_01",
    occasion: "WEDDING",
    tier: "SAFEST",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "classic"],
    vibe: "safe",
    formality_level: 5,
    confidence_score: 8,
    palette: ["navy", "white", "black"],
    image_url: "/images/wedding_safest_01.jpg",
    title: "Modern Classic",
    items: {
      top: "Slim-cut navy suit with a crisp white shirt",
      bottom: "Slim matching suit trousers",
      shoes: "Black oxfords",
    },
    reason: "Modern, fitted tailoring for a sharp formal impression.",
  },
  {
    id: "wedding_safest_highcontrast_01",
    occasion: "WEDDING",
    tier: "SAFEST",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE", "PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "safe",
    formality_level: 5,
    confidence_score: 9,
    palette: ["black", "crisp white", "black"],
    image_url: "/images/wedding_safest_01.jpg",
    title: "High Contrast Formal",
    items: {
      top: "Black suit with a crisp white shirt",
      bottom: "Matching suit trousers",
      shoes: "Black oxfords",
    },
    reason: "Bold contrast that matches high-contrast features perfectly.",
  },
  
  // WEDDING - SHARPER (6 variants)
  {
    id: "wedding_sharper_cool_01",
    occasion: "WEDDING",
    tier: "SHARPER",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 9,
    palette: ["charcoal", "white", "silver"],
    image_url: "/images/wedding_sharper_01.jpg",
    title: "Cool Elevated",
    items: {
      top: "Charcoal suit with a crisp white shirt",
      bottom: "Matching suit trousers",
      shoes: "Black leather shoes",
      extras: "Silver tie clip",
    },
    reason: "Cool sophistication with subtle refined details.",
  },
  {
    id: "wedding_sharper_warm_01",
    occasion: "WEDDING",
    tier: "SHARPER",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 8,
    palette: ["navy", "cream", "gold"],
    image_url: "/images/wedding_sharper_01.jpg",
    title: "Warm Elevated",
    items: {
      top: "Navy suit with a cream shirt",
      bottom: "Matching suit trousers",
      shoes: "Brown leather shoes",
      extras: "Gold tie clip",
    },
    reason: "Warm elegance with refined details for a memorable presence.",
  },
  {
    id: "wedding_sharper_neutral_01",
    occasion: "WEDDING",
    tier: "SHARPER",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 9,
    palette: ["charcoal", "white", "black"],
    image_url: "/images/wedding_sharper_01.jpg",
    title: "Sharp Formal",
    items: {
      top: "Charcoal suit with a crisp shirt",
      bottom: "Matching suit trousers",
      shoes: "Black leather shoes",
      extras: "Tie (optional)",
    },
    reason: "Sharper option if you want a more serious formal presence.",
  },
  {
    id: "wedding_sharper_broader_01",
    occasion: "WEDDING",
    tier: "SHARPER",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 8,
    palette: ["charcoal", "navy", "black"],
    image_url: "/images/wedding_sharper_01.jpg",
    title: "Commanding Formal",
    items: {
      top: "Charcoal suit with soft shoulders and a navy shirt",
      bottom: "Matching suit trousers with straight leg",
      shoes: "Black leather shoes",
      extras: "Dark tie",
    },
    reason: "Authoritative presence with refined, balanced tailoring.",
  },
  {
    id: "wedding_sharper_slim_01",
    occasion: "WEDDING",
    tier: "SHARPER",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["medium", "high"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 8,
    palette: ["black", "white", "charcoal"],
    image_url: "/images/wedding_sharper_01.jpg",
    title: "Modern Sharp",
    items: {
      top: "Slim-cut charcoal suit with a crisp white shirt",
      bottom: "Slim matching suit trousers",
      shoes: "Black leather shoes",
      extras: "Minimal black tie",
    },
    reason: "Modern, sharp tailoring for a contemporary formal impression.",
  },
  {
    id: "wedding_sharper_elevated_01",
    occasion: "WEDDING",
    tier: "SHARPER",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["PREMIUM"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["high"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["elevated"],
    vibe: "sharp",
    formality_level: 5,
    confidence_score: 9,
    palette: ["midnight navy", "crisp white", "black"],
    image_url: "/images/wedding_sharper_01.jpg",
    title: "Elite Formal",
    items: {
      top: "Midnight navy suit with a crisp white shirt",
      bottom: "Matching suit trousers",
      shoes: "Black leather shoes",
      extras: "Silver cufflinks and pocket square",
    },
    reason: "Elite elegance for the most significant occasions.",
  },
  
  // WEDDING - RELAXED (6 variants)
  {
    id: "wedding_relaxed_cool_01",
    occasion: "WEDDING",
    tier: "RELAXED",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["cool"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 4,
    confidence_score: 8,
    palette: ["light grey", "white", "brown"],
    image_url: "/images/wedding_relaxed_01.jpg",
    title: "Cool Relaxed",
    items: {
      top: "Light grey blazer with an open-collar white shirt",
      bottom: "Light grey tailored trousers",
      shoes: "Brown loafers",
    },
    reason: "Cool, relaxed elegance for a comfortable wedding look.",
  },
  {
    id: "wedding_relaxed_warm_01",
    occasion: "WEDDING",
    tier: "RELAXED",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["warm"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 4,
    confidence_score: 8,
    palette: ["tan", "cream", "brown"],
    image_url: "/images/wedding_relaxed_01.jpg",
    title: "Warm Relaxed",
    items: {
      top: "Tan blazer with an open-collar cream shirt",
      bottom: "Tan tailored trousers",
      shoes: "Brown loafers",
    },
    reason: "Warm, relaxed elegance for an inviting wedding presence.",
  },
  {
    id: "wedding_relaxed_neutral_01",
    occasion: "WEDDING",
    tier: "RELAXED",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["neutral"],
    contrast_fit: ["medium"],
    body_type_fit: ["slim", "athletic", "broader"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 4,
    confidence_score: 9,
    palette: ["light", "white", "brown"],
    image_url: "/images/wedding_relaxed_01.jpg",
    title: "Relaxed Elegant",
    items: {
      top: "Light blazer with an open-collar shirt",
      bottom: "Tailored trousers",
      shoes: "Loafers",
    },
    reason: "Elegant but more relaxed for a comfortable wedding look.",
  },
  {
    id: "wedding_relaxed_broader_01",
    occasion: "WEDDING",
    tier: "RELAXED",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["neutral", "cool"],
    contrast_fit: ["medium"],
    body_type_fit: ["broader"],
    taste_fit: ["classic"],
    vibe: "relaxed",
    formality_level: 4,
    confidence_score: 8,
    palette: ["navy", "slate", "brown"],
    image_url: "/images/wedding_relaxed_01.jpg",
    title: "Relaxed Structure",
    items: {
      top: "Navy unstructured blazer with an open-collar slate shirt",
      bottom: "Navy straight-leg trousers",
      shoes: "Brown loafers",
    },
    reason: "Relaxed formality with clean lines for balanced elegance.",
  },
  {
    id: "wedding_relaxed_slim_01",
    occasion: "WEDDING",
    tier: "RELAXED",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["cool", "neutral"],
    contrast_fit: ["low", "medium"],
    body_type_fit: ["slim"],
    taste_fit: ["minimalist", "classic"],
    vibe: "relaxed",
    formality_level: 4,
    confidence_score: 8,
    palette: ["light grey", "white", "tan"],
    image_url: "/images/wedding_relaxed_01.jpg",
    title: "Light Modern",
    items: {
      top: "Slim light grey blazer with an open-collar white shirt",
      bottom: "Light grey slim trousers",
      shoes: "Tan loafers",
    },
    reason: "Light, modern elegance for a fresh wedding look.",
  },
  {
    id: "wedding_relaxed_lowcontrast_01",
    occasion: "WEDDING",
    tier: "RELAXED",
    location: ["HOTEL", "OUTDOOR_VENUE"],
    time: ["DAY", "NIGHT"],
    setting: ["INDOOR", "OUTDOOR", "BOTH"],
    budget: ["MID_RANGE"],
    skin_tone_fit: ["neutral", "warm"],
    contrast_fit: ["low"],
    body_type_fit: ["slim", "athletic"],
    taste_fit: ["minimalist", "classic"],
    vibe: "relaxed",
    formality_level: 4,
    confidence_score: 8,
    palette: ["sand", "cream", "taupe"],
    image_url: "/images/wedding_relaxed_01.jpg",
    title: "Soft Elegant",
    items: {
      top: "Sand blazer with an open-collar cream shirt",
      bottom: "Taupe tailored trousers",
      shoes: "Light brown loafers",
    },
    reason: "Soft, tonal palette for an understated, elegant presence.",
  },
];

// ============= MATRIX UTILITIES =============

// Get all valid matrix outfits
export function getValidMatrixOutfits(): MatrixOutfitEntry[] {
  return OUTFIT_MATRIX.filter(outfit => 
    outfit.image_url && 
    outfit.items?.top && 
    outfit.items?.bottom && 
    outfit.items?.shoes &&
    outfit.title &&
    outfit.reason &&
    outfit.occasion &&
    outfit.tier
  );
}

// Get outfits by occasion
export function getMatrixOutfitsByOccasion(occasion: OccasionType): MatrixOutfitEntry[] {
  return getValidMatrixOutfits().filter(outfit => outfit.occasion === occasion);
}

// Get outfits by tier
export function getMatrixOutfitsByTier(tier: TierType): MatrixOutfitEntry[] {
  return getValidMatrixOutfits().filter(outfit => outfit.tier === tier);
}
